//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSoftClean.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidosArea()
        {
            this.DetalleLevantamiento = new HashSet<DetalleLevantamiento>();
        }
    
        public int id { get; set; }
        public string AreaIns { get; set; }
        public Nullable<int> IdModEqDos { get; set; }
        public Nullable<int> IdDosEstLim { get; set; }
        public Nullable<int> IdProdQuim { get; set; }
        public Nullable<int> IdModJab { get; set; }
        public Nullable<int> IdCepInBas { get; set; }
        public Nullable<int> IdTipMaqLav { get; set; }
        public Nullable<int> IdDosLav { get; set; }
        public Nullable<int> IdPorGalon { get; set; }
    
        public virtual AdmCepInBas AdmCepInBas { get; set; }
        public virtual AdmDosEstLim AdmDosEstLim { get; set; }
        public virtual AdmDosLav AdmDosLav { get; set; }
        public virtual AdmModEqDos AdmModEqDos { get; set; }
        public virtual AdmModJab AdmModJab { get; set; }
        public virtual AdmPortGalon AdmPortGalon { get; set; }
        public virtual AdmProdQuim AdmProdQuim { get; set; }
        public virtual AdmTipMaqLav AdmTipMaqLav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleLevantamiento> DetalleLevantamiento { get; set; }
    }
}
